name: Terraform Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: "Environment to deploy to (e.g., dev, prod)"
        type: string
        required: true
        default: dev
      terraform-action:
        description: "Terraform Command: plan or apply"
        type: string
        required: false
        default: plan
      terraform-directory:
        description:
        type: string
        required: false
        default: infra/terraform

    secrets:
      GCP_CREDENTIALS:
        description: "Service account JSON"
        required: true
      TF_STATE_BUCKET:
        description: "GCS bucket for Terraform state"
        required: true
      GCP_PROJECT:
        description: "Name of the GCP project"
        required: true
      STATE_SA_EMAIL:
        description: "Service Account email"
        required: true
      INVOKER_MEMBER:
        description: "SA invoker service"
        required: true

jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    env:
      TF_VAR_gcp_project      : ${{ secrets.GCP_PROJECT }}
      TF_VAR_tf_state_bucket  : ${{ secrets.TF_STATE_BUCKET }}
      TF_VAR_state_sa_email   : ${{ secrets.STATE_SA_EMAIL}}
      TF_VAR_invoker_member   : ${{ secrets.INVOKER_MEMBER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "CONFIG_DIR=configs/${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Compute tfvars file path
        run: echo "TFVARS_FILE=config/${{ inputs.environment }}.tfvars" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          cd ${{ inputs.terraform-directory }}
          terraform init \
            -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" \
            -backend-config="prefix=${{ inputs.environment }}/terraform/state"

      - name: Terraform Plan
        if: ${{ inputs.terraform-action == 'plan' }}
        run: |
          cd ${{ inputs.terraform-directory }}
          terraform plan -lock=false -var-file="$TFVARS_FILE" -out=tfplan
          terraform show -no-color tfplan > plan.txt

      - name: Terraform Apply
        if: ${{ inputs.terraform-action == 'apply' }}
        run: |
          cd ${{ inputs.terraform-directory }}
          terraform apply -var-file="$TFVARS_FILE" --auto-approve

      - name: Terraform Destroy
        if: ${{ inputs.terraform-action == 'destroy' }}
        run: |
          cd ${{ inputs.terraform-directory }}
          terraform destroy -var-file="$TFVARS_FILE" --auto-approve
